In [48]:
# list, tuple, set, dic, numpy, pandas
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [49]:
v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [50]:
v1 = np.arange(5)
print(f'v1의 값은 {v1}')

v1의 값은 [0 1 2 3 4]


In [51]:
v2 = np.arange(1, 10, 2,  dtype=int)
print(f'v2의 값은 {v2}')

v2의 값은 [1 3 5 7 9]


In [52]:
v3 = np.arange(3.5, 10.5, 2,  dtype=float)
print(f'v3의 값은 {v2}')

v3의 값은 [1 3 5 7 9]


In [53]:
v4 = np.arange(1, 10, 2)**2
print(f'v4의 제곱 값은 {v4}')

v4의 제곱 값은 [ 1  9 25 49 81]


In [54]:
v4 = np.arange(1, 10, 2)**3
print(f'v4의 3제곱 값은 {v4}')

v4의 3제곱 값은 [  1  27 125 343 729]


In [55]:
v5 = np.arange(12)
print(v5)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [56]:
v6 = v5.reshape(2, 6)
print(v6)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [57]:
v6 = v5.reshape(2, 6, order='F')
print(v6)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [58]:
v7 = np.arange(1, 5).reshape(2, 2)
print(v7)
print(np.add(v7, v7))
print(np.subtract(v7, v7))
print(np.multiply(v7, v7))
print(np.dot(v7, v7))

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [59]:
a = Series([1, 3, 5, 7])
print(a)

0    1
1    3
2    5
3    7
dtype: int64


In [60]:
print(a.values)

[1 3 5 7]


In [62]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)


In [65]:
a2 = Series([1,3,5,7,], index=['a','b','c','d'])
print(a2)

a    1
b    3
c    5
d    7
dtype: int64
